name: Run Model Training

on:
    workflow_dispatch:
        inputs:
            run_name:
                description: 'Name of the W&B run'
                required: true
                default: 'bert-tiny-imdb-run'
            dataset_name:
                description: 'Name of the Hugging Face dataset to use'
                required: true
                default: 'moizasghar/imdb-small-5k'
            testing:
                description: 'Whether to run in testing mode (true/false)'
                required: true
                default: 'false'
        
jobs:
    train-model:
        runs-on: ubuntu-latest
        env:
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
            RUN_NAME: ${{ github.event.inputs.run_name }}
            DATASET_NAME: ${{ github.event.inputs.dataset_name }}
            TESTING: ${{ github.event.inputs.testing }}

        steps:
            - name: Pull the image from Docker Hub
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/bert-tiny-sentiment:latest

            - name: Run the training container
              run: docker run -e API_KEY=${{ secrets.WANDB_API_KEY }} -e WANDB_RUN_NAME=${{ github.event.inputs.run_name }} -e DATASET_NAME=${{ github.event.inputs.dataset_name }} -e TESTING=${{ github.event.inputs.testing }} ${{ secrets.DOCKER_USERNAME }}/bert-tiny-sentiment:latest
            